### PR TITLE
Add Crate chart & helm repo

### PR DESCRIPTION
**Pull request by OJFord**
## Summary of the changes / Why this is an improvement

Allow users to `helm repo add crate <url> && helm install crate/crate` to install crate on their k8s cluster, where `<url>` will be https://crate.github.io/helm-charts once GitHub Pages is enabled for 'master branch /docs directory' in this repo's settings.

For example, on my fork `helm` can use:
https://ojford.github.io/crate-helm-charts

(in the browser, see https://ojford.github.io/crate-helm-charts/index.yaml)

NB I also have a branch prepared at https://github.com/OJFord/hub/tree/add-crate to register this repo with Helm Hub, although the 'maintainer(s)' listed there should be someone with access to this (git) repository rather than me - since the docs say it's needed as a contact point in case of the (helm) repository going offline or similar issues.

Thanks to @taliaga for early work on this chart, as well as @chaudum and @fabianbaier for feedback in helm/charts#16318.

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by mfussenegger** [comment]
> although the 'maintainer(s)' listed there should be someone with access to this (git) repository rather than me

If it is okay for you we would add contributor rights for you on this repo and also declare in the README that this is mostly a community maintained repository.

**Comment by OJFord** [comment]
Sure, no problem.

**Review by mfussenegger — APPROVED** [review]

**Comment by OJFord** [comment]
Thanks @mfussenegger!

Could you enable GitHub pages for the `/docs` directory in the repo 'Settings' tab? (It seems 'Collaborator's don't have access to that.)

That should then make the index for `helm repo add` (as described in readme usage) available here:
http://crate.github.io/helm-charts/index.yaml

**Comment by mfussenegger** [comment]
@OJFord done

**Pull request merged**
